language: R
sudo: no
cache: packages
after_success: Rscript -e 'covr::coveralls(type = "all")'
warnings_are_errors: yes

dist: precise

os:
  - linux
  - osx

before_deploy: if [ "$TRAVIS_OS_NAME" == "osx" ]; then rm -f *.tar.gz fi
r_check_args: --as-cran --install-args=--build


before_install:
  - export PROJ_DIR=`basename $PWD`
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}  
  - cat DESCRIPTION
  - export PACKAGE_NAME=`package_name`  
  - Rscript -e 'source("https://install-github.me/mangothecat/callr")'
  - remove_neuroc_packages
  - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
  # does all the clang exports
  - x=`export_clang_cxx`; eval ${x}
  - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"  
  - clang_cxx  
  - export cmake_version="3.4"
  - cmake --version
  - x=`cmake_setup`; echo "${x}"; eval ${x};
  - cmake --version
  - export ants_user=stnava
  - install_missing_remote_deps ${ants_user}/ITKR 
  - echo "Done Installing Missing Deps"
  - gh_binary_install ${ants_user}/ITKR ;
  - cat DESCRIPTION
  - install_remotes_no_dep
  - cat DESCRIPTION
  - echo $PATH ;

deploy:
  provider: releases
  skip_cleanup: yes
  file_glob: yes
  file: robex*.t*gz
  'on':
    tags: yes
    repo: muschellij2/robex

